### ISSUE TITLE
Make the robot sing

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#20]
Falcon 500's are a monophonic instrument which can play musical notes.

[Not kidding](https://www.reddit.com/r/FRC/comments/f0h8oq/falcon_500_megalovania/)

We will have at least four of them.

Pick your favorite music that can be played on a piano using only four really fast fingers.

Here's some info on making the ".chrp" files to describe that music: https://www.chiefdelphi.com/t/chrp-audio-files-for-talonfx-music/376366

Reference [this example](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/Java%20Talon%20FX%20(Falcon%20500)/Music%20-%20Orchestra/src/main/java/frc/robot/Robot.java) for playing back .chrp files on our robot.

Fun is a core value

**Comment by LuckyScout06** [comment]
how many different songs do you want
