### ISSUE TITLE
Arduino/LED Intial Support

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#22]
[We like pretty lights on our robot](https://www.youtube.com/watch?v=jIFfaYls2B4) 

These are usually run off of a separate processor called an Arduino. It's programmed in a different language than java - [here's last year's for reference](https://github.com/RobotCasserole1736/RobotCasserole2020/tree/master/LEDS/CasseroleLED)

[Here's a tutorial on making an arduino control those LED's](https://randomnerdtutorials.com/guide-for-ws2812b-addressable-rgb-led-strip-with-arduino/)

[Here's the code editor and toolchain for Arduino](https://www.arduino.cc/en/software)

We should have arduinos around programming area, see if you can find one.

I'm not sure what we have in terms of LED strips, but we'll need to get them hooked up to be powered from the test board and everything - poke a mentor for help if needed. Especially once we order them :)

Get some cool looking patterns put together. FOr now, we're just [looking for nifty/pretty ideas.](https://www.youtube.com/watch?v=7VAXrPRxD7I) anything you come up with is fair game, ask a mentor if you're not sure how to make code to do a thing happen.

In a future activitiyl, we'll work on having multiple patterns available, and picking them from the roboRIO.

**Comment by imdunne8** [comment]
Quite a few interesting pattern ideas (with code) here: https://www.tweaking4all.com/hardware/arduino/adruino-led-strip-effects/

**Comment by imdunne8** [comment]
Implementing it in our 2022 code will look very similar to 2020.
[Controller Code](https://github.com/RobotCasserole1736/RobotCasserole2020/blob/master/RobotCasserole2020/src/main/java/frc/robot/LEDController.java)
[Implementation in Robot.java](https://github.com/RobotCasserole1736/RobotCasserole2020/blob/ac2b684dcb55423456a04409782656e690a973c7/RobotCasserole2020/src/main/java/frc/robot/Robot.java#L70)
