### ISSUE TITLE
Update Dashboard Layout

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#32]
Update the dashboard layout to contain:

1) a dial for Shooter actual speed
2) a dial for pneumatics pressure
3) The swerve drive state widget (already present)
4) The field position widget (already present)
5) The autonomous selector (already present)

Feel free to move stuff around as needed to make it look pretty.

Also feel free to add more icons or other fun things if you want. No huge issue if we have to change it later.

**Comment by imdunne8** [comment]
A couple more things to add:
Shooter Spooled Up (exists but is commented out)
- Need to create a variable at the top with signal `db_shooterSpoolup` and get the data from the Shooter getSpooledUp method

Climber Extended (icon, similar to master caution icon)
Climber Tilted (icon, similar to master caution icon)
