### ISSUE TITLE
Add Driver Drivetrain Input Smoothing Strategies

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#43]
The robot is currently very hard to control by just providing raw inputs. However, we can "massage" driver inputs to help improve this.

This issue is to add a number of mitigations, with reasonable guesses at initial values.

# Slew Rate Limiter

See [docs here](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/filters/slew-rate-limiter.html). A slew rate limiter will reduce the maximum rate of change to something realistic, in case the driver "pulses" the joystick and provides unreaslitic input.

Add three of these to the driver input class, one for fwd/rev, rotate, and left/rigth motion each. Set all to have a slew rate of 0 to full in 0.3 sec to start.

# Driver Max Velocity

The driver class currently outputs raw joystick [-1, 1] range outputs. To match with autonomous, it should output physical units ("meters per second" and "radians per second") velocities. Currently, this conversion is being done inside Robot.java. Move the conversion inside DriverInterface.java.

Make new constants for the maximum translational and rotational velocity the driver can command. Base them on the constants for the robot's maximum velocity, but multiplied by some scalar in the range (0.0, 1.0]. Right now, we're using 0.5 for the translational velocities, and 1.0 for the rotational velocity. 

# Overall Rearchitecture

Add signals to track the driver's "raw joystick" inputs, as well as the fully-massaged, physical units outputs. There should be six total (three raw, three massaged).

The order of the new functionality added should be:

`raw_joystick -> Deadband -> slew rate limit -> convert to physical units -> output`

Using calibrations for the slew rate limit and the max velocity scalar would make tuning faster, might be worth doing.

**Comment by imdunne8** [comment]
Abby finished this up tonight and tested out in sim
