### ISSUE TITLE
Set up driver camera

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#51]
1) Grab a Raspberry Pi from the software shelves
2) Flash on the [WPILib Pi image](https://github.com/wpilibsuite/WPILibPi/releases)
3) Attach a Raspberry Pi camera (will have the flat ribbon cable, not USB)
4) Work with CAD to design a 3d-printed mount for the camera. Something [like this](https://www.thingiverse.com/thing:92208). Find a way to get it mounted on the robot
5) Hook stuff up to the testboard as you'd expect it to be on the robot
6) Set up a stream on the driver dashboard to show the camera. Make sure it can be full-screened.

**Comment by imdunne8** [comment]
Tested this out tonight on the 2022 robot and everything seems to work well.  Still need to decide on an actual camera module (the bigger ones from 2020 aren't good for this use case) and then a printed case
