### ISSUE TITLE
Change LED colors based on robot conditions

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#54]
In general, we want the LED's on the robot to indicate useful things to the driver, to increase their ability to be "heads up" but still get feedback from the robot.

Trigger special patterns on the robot for the following conditions:

1) Two balls in the elevator
2) Shooter spooled up
3) Match time < 30 sec remaining

At all other times, just make it pretty!

**Comment by LuckyScout06** [comment]
two balls- Green
Shooter spooled- Blue
Match time- Flashing red (with a siren)
