### ISSUE TITLE
readme.md cleanup

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#55]
The current readme has a few small-ish issues:

No logo for this year
Baby yoda picture doesn't actually exist
Log file snagger and log viewer aren't actually there, and won't be used this year. The website has supplanted the need for them.
Paper chicken image is missing

Remove references to the missing pictures to clean it up, or find an appropriate substitute image to put in place.

**Comment by gojira2021** [comment]
I'll work on this.

**Comment by gojira2021** [comment]
Added Fractal and other minor and unequally important things.
