### ISSUE TITLE
Add "YEET_CARGO" state to shooter

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#60]
in addition to low goal and high goal, add a `YEET_CARGO` state to the shooter command enum.

When `YEET_CARGO` is commanded, run the shooter at maximum velocity (Let's say ~5200 RPM) and feed balls when we get there as usual.

Add support to the driver input to have a button to command `YEET_CARGO`.

**Comment by LuckyScout06** [comment]
Can we add a speaker that yells YEET
